// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.DTO;

public partial class TourBidListResult
{
    public int TourBidId { get; set; }

    public int AccountId { get; set; }
    public string CustomerName { get; set; }

    public DateTime CreatedAt { get; set; }

    public int PlaceRequested { get; set; }
    public string PlaceRequestedName { get; set; }

    public string Status { get; set; }

    public string Content { get; set; }

    public float? MaxPrice { get; set; }
    public int LikeCount { get; set; }
    public bool IsLiked { get; set; }
    public string CustomerImg { get; set; }
}