// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Repositories.Models;

namespace Repositories.Context;

public partial class TourmateContext : DbContext
{
    public TourmateContext()
    {
    }

    public TourmateContext(DbContextOptions<TourmateContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<AccountMembership> AccountMemberships { get; set; }

    public virtual DbSet<ActiveArea> ActiveAreas { get; set; }

    public virtual DbSet<Bid> Bids { get; set; }

    public virtual DbSet<Blog> Blogs { get; set; }

    public virtual DbSet<BlogComment> BlogComments { get; set; }

    public virtual DbSet<BlogCommentReply> BlogCommentReplies { get; set; }

    public virtual DbSet<BlogLike> BlogLikes { get; set; }

    public virtual DbSet<Contact> Contacts { get; set; }

    public virtual DbSet<Conversation> Conversations { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Cvapplication> Cvapplications { get; set; }

    public virtual DbSet<Feedback> Feedbacks { get; set; }

    public virtual DbSet<Invoice> Invoices { get; set; }

    public virtual DbSet<MembershipPackage> MembershipPackages { get; set; }

    public virtual DbSet<Message> Messages { get; set; }

    public virtual DbSet<News> News { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<RefreshToken> RefreshTokens { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<SystemRevenue> SystemRevenues { get; set; }

    public virtual DbSet<TourBid> TourBids { get; set; }

    public virtual DbSet<TourGuide> TourGuides { get; set; }

    public virtual DbSet<TourGuideDesc> TourGuideDescs { get; set; }

    public virtual DbSet<TourGuideRevenue> TourGuideRevenues { get; set; }

    public virtual DbSet<TourService> TourServices { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Account>(entity =>
        {
            entity.HasKey(e => e.AccountId).HasName("PK__Account__F267251E2DC3FCD5");

            entity.ToTable("Account");

            entity.HasIndex(e => e.Email, "UQ__Account__AB6E6164126F9265").IsUnique();

            entity.Property(e => e.AccountId).HasColumnName("accountId");
            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("createdDate");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.Password)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("password");
            entity.Property(e => e.RoleId).HasColumnName("roleId");
            entity.Property(e => e.Status).HasColumnName("status");

            entity.HasOne(d => d.Role).WithMany(p => p.Accounts)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKAccount946763");
        });

        modelBuilder.Entity<AccountMembership>(entity =>
        {
            entity.HasKey(e => e.AccountMembershipId).HasName("PK__AccountM__1C86D62940CF23A4");

            entity.ToTable("AccountMembership");

            entity.Property(e => e.AccountMembershipId).HasColumnName("accountMembershipId");
            entity.Property(e => e.AccountId).HasColumnName("accountId");
            entity.Property(e => e.EndDate).HasColumnName("endDate");
            entity.Property(e => e.IsActive).HasColumnName("isActive");
            entity.Property(e => e.MembershipPackageId).HasColumnName("membershipPackageId");
            entity.Property(e => e.StartDate).HasColumnName("startDate");

            entity.HasOne(d => d.Account).WithMany(p => p.AccountMemberships)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKAccountMem798455");

            entity.HasOne(d => d.MembershipPackage).WithMany(p => p.AccountMemberships)
                .HasForeignKey(d => d.MembershipPackageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKAccountMem974204");
        });

        modelBuilder.Entity<ActiveArea>(entity =>
        {
            entity.HasKey(e => e.AreaId).HasName("PK__ActiveAr__52936C57CD7409BF");

            entity.ToTable("ActiveArea");

            entity.Property(e => e.AreaId).HasColumnName("areaId");
            entity.Property(e => e.AreaContent)
                .IsRequired()
                .HasColumnName("areaContent");
            entity.Property(e => e.AreaName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("areaName");
            entity.Property(e => e.AreaSubtitle)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("areaSubtitle");
            entity.Property(e => e.AreaTitle)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("areaTitle");
            entity.Property(e => e.AreaType)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("areaType");
            entity.Property(e => e.BannerImg)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("bannerImg");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
        });

        modelBuilder.Entity<Bid>(entity =>
        {
            entity.HasKey(e => e.BidId).HasName("PK__Bid__48E98F58ACB534F4");

            entity.ToTable("Bid");

            entity.Property(e => e.BidId).HasColumnName("bidId");
            entity.Property(e => e.Amount).HasColumnName("amount");
            entity.Property(e => e.Comment).HasColumnName("comment");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("status");
            entity.Property(e => e.TourBidId).HasColumnName("tourBidId");
            entity.Property(e => e.TourGuideId).HasColumnName("tourGuideId");

            entity.HasOne(d => d.TourBid).WithMany(p => p.Bids)
                .HasForeignKey(d => d.TourBidId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKBid659809");

            entity.HasOne(d => d.TourGuide).WithMany(p => p.Bids)
                .HasForeignKey(d => d.TourGuideId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKBid623728");
        });

        modelBuilder.Entity<Blog>(entity =>
        {
            entity.HasKey(e => e.BlogId).HasName("PK__Blog__FA0AA72DF38C74C8");

            entity.ToTable("Blog");

            entity.Property(e => e.BlogId).HasColumnName("blogId");
            entity.Property(e => e.AccountId).HasColumnName("accountId");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnName("content");
            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("createdDate");
            entity.Property(e => e.IsDeleted).HasColumnName("isDeleted");
            entity.Property(e => e.Media)
                .IsRequired()
                .HasColumnName("media");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");

            entity.HasOne(d => d.Account).WithMany(p => p.Blogs)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKBlog316425");
        });

        modelBuilder.Entity<BlogComment>(entity =>
        {
            entity.HasKey(e => e.BlogCommentId).HasName("PK__BlogComm__555BBA7E02884DA3");

            entity.ToTable("BlogComment");

            entity.Property(e => e.BlogCommentId).HasColumnName("blogCommentId");
            entity.Property(e => e.AccountId).HasColumnName("accountId");
            entity.Property(e => e.BlogId).HasColumnName("blogId");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnName("content");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.IsDeleted).HasColumnName("isDeleted");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");

            entity.HasOne(d => d.Account).WithMany(p => p.BlogComments)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKBlogCommen856142");

            entity.HasOne(d => d.Blog).WithMany(p => p.BlogComments)
                .HasForeignKey(d => d.BlogId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKBlogCommen331450");
        });

        modelBuilder.Entity<BlogCommentReply>(entity =>
        {
            entity.HasKey(e => e.BlogCommentReplyId).HasName("PK__BlogComm__BE4948515F66F0A2");

            entity.ToTable("BlogCommentReply");

            entity.Property(e => e.BlogCommentReplyId).HasColumnName("blogCommentReplyId");
            entity.Property(e => e.AccountId).HasColumnName("accountId");
            entity.Property(e => e.BlogCommentId).HasColumnName("blogCommentId");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnName("content");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.IsDeleted).HasColumnName("isDeleted");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");

            entity.HasOne(d => d.Account).WithMany(p => p.BlogCommentReplies)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKBlogCommen891262");

            entity.HasOne(d => d.BlogComment).WithMany(p => p.BlogCommentReplies)
                .HasForeignKey(d => d.BlogCommentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKBlogCommen494206");
        });

        modelBuilder.Entity<BlogLike>(entity =>
        {
            entity.HasKey(e => e.BlogLikeId).HasName("PK__BlogLike__E52253F99D4EE902");

            entity.ToTable("BlogLike");

            entity.Property(e => e.BlogLikeId).HasColumnName("blogLikeId");
            entity.Property(e => e.AccountId).HasColumnName("accountId");
            entity.Property(e => e.BlogId).HasColumnName("blogId");

            entity.HasOne(d => d.Account).WithMany(p => p.BlogLikes)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKBlogLike84009");

            entity.HasOne(d => d.Blog).WithMany(p => p.BlogLikes)
                .HasForeignKey(d => d.BlogId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKBlogLike559316");
        });

        modelBuilder.Entity<Contact>(entity =>
        {
            entity.HasKey(e => e.ContactId).HasName("PK__Contact__7121FD354BD0D0C2");

            entity.ToTable("Contact");

            entity.Property(e => e.ContactId).HasColumnName("contactId");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnName("content");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("fullName");
            entity.Property(e => e.IsProcessed).HasColumnName("isProcessed");
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("phone");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("title");
        });

        modelBuilder.Entity<Conversation>(entity =>
        {
            entity.HasKey(e => e.ConersationId).HasName("PK__Conversa__6952075F10BE9D6E");

            entity.ToTable("Conversation");

            entity.Property(e => e.ConersationId).HasColumnName("conersationId");
            entity.Property(e => e.Account1Id).HasColumnName("account1Id");
            entity.Property(e => e.Account2Id).HasColumnName("account2Id");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("createdAt");

            entity.HasOne(d => d.Account1).WithMany(p => p.ConversationAccount1s)
                .HasForeignKey(d => d.Account1Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKConversati600223");

            entity.HasOne(d => d.Account2).WithMany(p => p.ConversationAccount2s)
                .HasForeignKey(d => d.Account2Id)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKConversati599262");
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.CustomerId).HasName("PK__Customer__B611CB7D8069BD69");

            entity.ToTable("Customer");

            entity.HasIndex(e => e.Phone, "UQ__Customer__B43B145FCC272FB7").IsUnique();

            entity.Property(e => e.CustomerId).HasColumnName("customerId");
            entity.Property(e => e.AccountId).HasColumnName("accountId");
            entity.Property(e => e.DateOfBirth).HasColumnName("dateOfBirth");
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("fullName");
            entity.Property(e => e.Gender)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("gender");
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("phone");

            entity.HasOne(d => d.Account).WithMany(p => p.Customers)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKCustomer62882");
        });

        modelBuilder.Entity<Cvapplication>(entity =>
        {
            entity.HasKey(e => e.CvApplicationId).HasName("PK__CVApplic__F753C8A2698460E0");

            entity.ToTable("CVApplication");

            entity.Property(e => e.CvApplicationId).HasColumnName("cvApplicationId");
            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("address");
            entity.Property(e => e.DateOfBirth).HasColumnName("dateOfBirth");
            entity.Property(e => e.Description).HasColumnName("description");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("fullName");
            entity.Property(e => e.Gender)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("gender");
            entity.Property(e => e.Image)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("image");
            entity.Property(e => e.Link)
                .HasMaxLength(255)
                .HasColumnName("link");
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("phone");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("status");
        });

        modelBuilder.Entity<Feedback>(entity =>
        {
            entity.HasKey(e => e.FeedbackId).HasName("PK__Feedback__2613FD24509B9F35");

            entity.ToTable("Feedback");

            entity.Property(e => e.FeedbackId).HasColumnName("feedbackId");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnName("content");
            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("createdDate");
            entity.Property(e => e.CustomerId).HasColumnName("customerId");
            entity.Property(e => e.IsDeleted).HasColumnName("isDeleted");
            entity.Property(e => e.Rating).HasColumnName("rating");
            entity.Property(e => e.TourGuideId).HasColumnName("tourGuideId");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");

            entity.HasOne(d => d.Customer).WithMany(p => p.Feedbacks)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKFeedback561761");

            entity.HasOne(d => d.TourGuide).WithMany(p => p.Feedbacks)
                .HasForeignKey(d => d.TourGuideId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKFeedback699513");
        });

        modelBuilder.Entity<Invoice>(entity =>
        {
            entity.HasKey(e => e.InvoiceId).HasName("PK__Invoice__1252416CFAF38655");

            entity.ToTable("Invoice");

            entity.Property(e => e.InvoiceId).HasColumnName("invoiceId");
            entity.Property(e => e.AreaId).HasColumnName("areaId");
            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasColumnName("createdDate");
            entity.Property(e => e.CustomerId).HasColumnName("customerId");
            entity.Property(e => e.EndDate)
                .HasColumnType("datetime")
                .HasColumnName("endDate");
            entity.Property(e => e.Note)
                .IsRequired()
                .HasColumnName("note");
            entity.Property(e => e.PeopleAmount)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("peopleAmount");
            entity.Property(e => e.Price).HasColumnName("price");
            entity.Property(e => e.StartDate)
                .HasColumnType("datetime")
                .HasColumnName("startDate");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.TourDesc)
                .IsRequired()
                .HasColumnName("tourDesc");
            entity.Property(e => e.TourGuideId).HasColumnName("tourGuideId");

            entity.HasOne(d => d.Area).WithMany(p => p.Invoices)
                .HasForeignKey(d => d.AreaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKInvoice643155");

            entity.HasOne(d => d.Customer).WithMany(p => p.Invoices)
                .HasForeignKey(d => d.CustomerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKInvoice303466");

            entity.HasOne(d => d.TourGuide).WithMany(p => p.Invoices)
                .HasForeignKey(d => d.TourGuideId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKInvoice441218");
        });

        modelBuilder.Entity<MembershipPackage>(entity =>
        {
            entity.HasKey(e => e.MembershipPackageId).HasName("PK__Membersh__FC12A4549504E653");

            entity.ToTable("MembershipPackage");

            entity.Property(e => e.MembershipPackageId).HasColumnName("membershipPackageId");
            entity.Property(e => e.BenefitDesc)
                .IsRequired()
                .HasColumnName("benefitDesc");
            entity.Property(e => e.Duration)
                .HasComment("in day")
                .HasColumnName("duration");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
            entity.Property(e => e.Price).HasColumnName("price");
        });

        modelBuilder.Entity<Message>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("PK__Message__4808B993A66E5886");

            entity.ToTable("Message");

            entity.Property(e => e.MessageId).HasColumnName("messageId");
            entity.Property(e => e.ConversationId).HasColumnName("conversationId");
            entity.Property(e => e.IsDeleted).HasColumnName("isDeleted");
            entity.Property(e => e.IsEdited).HasColumnName("isEdited");
            entity.Property(e => e.IsRead).HasColumnName("isRead");
            entity.Property(e => e.MessageText)
                .IsRequired()
                .HasColumnName("messageText");
            entity.Property(e => e.MessageType)
                .HasMaxLength(50)
                .HasColumnName("messageType");
            entity.Property(e => e.SendAt)
                .HasColumnType("datetime")
                .HasColumnName("sendAt");
            entity.Property(e => e.SenderId).HasColumnName("senderId");

            entity.HasOne(d => d.Conversation).WithMany(p => p.Messages)
                .HasForeignKey(d => d.ConversationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKMessage780995");

            entity.HasOne(d => d.Sender).WithMany(p => p.Messages)
                .HasForeignKey(d => d.SenderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKMessage122587");
        });

        modelBuilder.Entity<News>(entity =>
        {
            entity.HasKey(e => e.NewsId).HasName("PK__News__5218041E33CC5821");

            entity.Property(e => e.NewsId).HasColumnName("newsId");
            entity.Property(e => e.BannerImg)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("bannerImg");
            entity.Property(e => e.Category)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("category");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnName("content");
            entity.Property(e => e.CreatedAt).HasColumnName("createdAt");            
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("title");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.PaymentId).HasName("PK__Payment__A0D9EFC64DF78991");

            entity.ToTable("Payment");

            entity.Property(e => e.PaymentId).HasColumnName("paymentId");
            entity.Property(e => e.AccountId).HasColumnName("accountId");
            entity.Property(e => e.CompleteDate)
                .HasColumnType("datetime")
                .HasColumnName("completeDate");
            entity.Property(e => e.InvoiceId).HasColumnName("invoiceId");
            entity.Property(e => e.MembershipPackageId).HasColumnName("membershipPackageId");
            entity.Property(e => e.PaymentMethod)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("momo/ vnpay")
                .HasColumnName("paymentMethod");
            entity.Property(e => e.PaymentType)
                .IsRequired()
                .HasMaxLength(50)
                .HasComment("membership / invoice")
                .HasColumnName("paymentType");
            entity.Property(e => e.Price).HasColumnName("price");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("status");

            entity.HasOne(d => d.Account).WithMany(p => p.Payments)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKPayment215705");

            entity.HasOne(d => d.Invoice).WithMany(p => p.Payments)
                .HasForeignKey(d => d.InvoiceId)
                .HasConstraintName("FKPayment939394");

            entity.HasOne(d => d.MembershipPackage).WithMany(p => p.Payments)
                .HasForeignKey(d => d.MembershipPackageId)
                .HasConstraintName("FKPayment16775");
        });

        modelBuilder.Entity<RefreshToken>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__RefreshT__3213E83F61ABA30B");

            entity.ToTable("RefreshToken");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.ExpireAt)
                .HasColumnType("datetime")
                .HasColumnName("expireAt");
            entity.Property(e => e.IsRevoked).HasColumnName("isRevoked");
            entity.Property(e => e.Token)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("token");
            entity.Property(e => e.UserId).HasColumnName("userId");

            entity.HasOne(d => d.User).WithMany(p => p.RefreshTokens)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKRefreshTok914650");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Role__CD98462A92AA519D");

            entity.ToTable("Role");

            entity.Property(e => e.RoleId).HasColumnName("roleId");
            entity.Property(e => e.RoleName)
                .HasMaxLength(50)
                .HasColumnName("roleName");
        });

        modelBuilder.Entity<SystemRevenue>(entity =>
        {
            entity.HasKey(e => e.SystemRevenueId).HasName("PK__SystemRe__EED5C17D14EC380F");

            entity.ToTable("SystemRevenue");

            entity.Property(e => e.SystemRevenueId).HasColumnName("systemRevenueId");
            entity.Property(e => e.PaymentId).HasColumnName("paymentId");
            entity.Property(e => e.Value).HasColumnName("value");

            entity.HasOne(d => d.Payment).WithMany(p => p.SystemRevenues)
                .HasForeignKey(d => d.PaymentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKSystemReve708422");
        });

        modelBuilder.Entity<TourBid>(entity =>
        {
            entity.HasKey(e => e.TourBid1).HasName("PK__TourBid__6359293A59282C50");

            entity.ToTable("TourBid");

            entity.Property(e => e.TourBid1).HasColumnName("tourBid");
            entity.Property(e => e.AccountId).HasColumnName("accountId");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnName("content");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("createdAt");
            entity.Property(e => e.IsDeleted).HasColumnName("isDeleted");
            entity.Property(e => e.MaxPrice).HasColumnName("maxPrice");
            entity.Property(e => e.PlaceRequested).HasColumnName("placeRequested");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("status");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime")
                .HasColumnName("updatedAt");

            entity.HasOne(d => d.Account).WithMany(p => p.TourBids)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKTourBid491964");

            entity.HasOne(d => d.PlaceRequestedNavigation).WithMany(p => p.TourBids)
                .HasForeignKey(d => d.PlaceRequested)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKTourBid682696");
        });

        modelBuilder.Entity<TourGuide>(entity =>
        {
            entity.HasKey(e => e.TourGuideId).HasName("PK__TourGuid__D466D4A201BE794C");

            entity.ToTable("TourGuide");

            entity.HasIndex(e => e.Phone, "UQ__TourGuid__B43B145FE9587D91").IsUnique();

            entity.Property(e => e.TourGuideId).HasColumnName("tourGuideId");
            entity.Property(e => e.AccountId).HasColumnName("accountId");
            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("address");
            entity.Property(e => e.DateOfBirth).HasColumnName("dateOfBirth");
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("fullName");
            entity.Property(e => e.Gender)
                .IsRequired()
                .HasMaxLength(10)
                .HasColumnName("gender");
            entity.Property(e => e.Image)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("image");
            entity.Property(e => e.Phone)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("phone");

            entity.HasOne(d => d.Account).WithMany(p => p.TourGuides)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKTourGuide28174");
        });

        modelBuilder.Entity<TourGuideDesc>(entity =>
        {
            entity.HasKey(e => e.TourGuideDescId).HasName("PK__TourGuid__5D853B51B873C1E5");

            entity.ToTable("TourGuideDesc");

            entity.Property(e => e.TourGuideDescId).HasColumnName("tourGuideDescId");
            entity.Property(e => e.AreaId).HasColumnName("areaId");
            entity.Property(e => e.Company)
                .HasMaxLength(255)
                .HasColumnName("company");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasColumnName("description");
            entity.Property(e => e.TourGuideId).HasColumnName("tourGuideId");
            entity.Property(e => e.YearOfExperience).HasColumnName("yearOfExperience");

            entity.HasOne(d => d.Area).WithMany(p => p.TourGuideDescs)
                .HasForeignKey(d => d.AreaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKTourGuideD540188");

            entity.HasOne(d => d.TourGuide).WithMany(p => p.TourGuideDescs)
                .HasForeignKey(d => d.TourGuideId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKTourGuideD742125");
        });

        modelBuilder.Entity<TourGuideRevenue>(entity =>
        {
            entity.HasKey(e => e.TourGuideRevenue1).HasName("PK__TourGuid__04961506CD011265");

            entity.ToTable("TourGuideRevenue");

            entity.Property(e => e.TourGuideRevenue1).HasColumnName("tourGuideRevenue");
            entity.Property(e => e.PaymentId).HasColumnName("paymentId");
            entity.Property(e => e.TourGuideId).HasColumnName("tourGuideId");
            entity.Property(e => e.Value).HasColumnName("value");

            entity.HasOne(d => d.Payment).WithMany(p => p.TourGuideRevenues)
                .HasForeignKey(d => d.PaymentId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKTourGuideR890450");

            entity.HasOne(d => d.TourGuide).WithMany(p => p.TourGuideRevenues)
                .HasForeignKey(d => d.TourGuideId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKTourGuideR267432");
        });

        modelBuilder.Entity<TourService>(entity =>
        {
            entity.HasKey(e => e.ServiceId).HasName("PK__TourServ__455070DFAA3CE893");

            entity.ToTable("TourService");

            entity.Property(e => e.ServiceId).HasColumnName("serviceId");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnName("content");
            entity.Property(e => e.CreatedDate).HasColumnName("createdDate");
            entity.Property(e => e.Duration).HasColumnName("duration");
            entity.Property(e => e.Image)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("image");
            entity.Property(e => e.IsDeleted).HasColumnName("isDeleted");
            entity.Property(e => e.Price).HasColumnName("price");
            entity.Property(e => e.ServiceName)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("serviceName");
            entity.Property(e => e.TourGuideId).HasColumnName("tourGuideId");

            entity.HasOne(d => d.TourGuide).WithMany(p => p.TourServices)
                .HasForeignKey(d => d.TourGuideId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FKTourServic281225");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}