// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class ActiveArea
{
    public int AreaId { get; set; }

    public string AreaName { get; set; }

    public string AreaTitle { get; set; }

    public string AreaSubtitle { get; set; }

    public string AreaContent { get; set; }

    public string BannerImg { get; set; }
    public string AreaType { get; set; }

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    public virtual ICollection<TourBid> TourBids { get; set; } = new List<TourBid>();

    public virtual ICollection<TourGuideDesc> TourGuideDescs { get; set; } = new List<TourGuideDesc>();
}