// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Bid
{
    public int BidId { get; set; }

    public int TourBidId { get; set; }

    public int TourGuideId { get; set; }

    public float Amount { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Comment { get; set; }

    public string Status { get; set; }

    public virtual TourBid TourBid { get; set; }

    public virtual TourGuide TourGuide { get; set; }
}