// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Customer
{
    public int CustomerId { get; set; }

    public string FullName { get; set; }

    public int AccountId { get; set; }

    public string Gender { get; set; }

    public DateOnly DateOfBirth { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();
}