// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class FileStorage
{
    public string Id { get; set; }

    public string FileName { get; set; }

    public string DownloadUrl { get; set; }

    public DateTime? UploadTime { get; set; }

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();
}