// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class Message
{
    public int MessageId { get; set; }

    public int ConversationId { get; set; }

    public int SenderId { get; set; }

    public string MessageText { get; set; }

    public DateTime SendAt { get; set; }

    public bool IsRead { get; set; }

    public bool IsEdited { get; set; }

    public bool IsDeleted { get; set; }

    public int? MessageTypeId { get; set; }

    public string FileId { get; set; }

    public virtual Conversation Conversation { get; set; }

    public virtual FileStorage File { get; set; }

    public virtual MessageType MessageType { get; set; }

    public virtual Account Sender { get; set; }
}