// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class MessageType
{
    public int MessageTypeId { get; set; }

    public string TypeName { get; set; }

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();
}