// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class News
{
    public int NewsId { get; set; }

    public string Title { get; set; }

    public DateOnly CreatedDate { get; set; }

    public bool IsDeleted { get; set; }

    public string Content { get; set; }

    public string BannerImg { get; set; }

    public virtual ICollection<NewsCategory> NewsCategories { get; set; } = new List<NewsCategory>();

    public virtual ICollection<NewsComment> NewsComments { get; set; } = new List<NewsComment>();
}