// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class News
{
    public int NewsId { get; set; }

    public string Title { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Content { get; set; }

    public string BannerImg { get; set; }

    public string Category { get; set; }
}