// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class TourGuideDesc
{
    public int TourGuideDescId { get; set; }

    public int TourGuideId { get; set; }

    public int? YearOfExperience { get; set; }

    public string Description { get; set; }

    public int AreaId { get; set; }

    public string Company { get; set; }

    public virtual ActiveArea Area { get; set; }

    public virtual TourGuide TourGuide { get; set; }
}