// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class TourGuide
{
    public int TourGuideId { get; set; }

    public string FullName { get; set; }

    public string Gender { get; set; }

    public DateOnly DateOfBirth { get; set; }

    public int AccountId { get; set; }

    public string Address { get; set; }

    public string Image { get; set; }

    public string Phone { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<Bid> Bids { get; set; } = new List<Bid>();

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    public virtual ICollection<TourGuideDesc> TourGuideDescs { get; set; } = new List<TourGuideDesc>();

    public virtual ICollection<TourGuideRevenue> TourGuideRevenues { get; set; } = new List<TourGuideRevenue>();

    public virtual ICollection<TourService> TourServices { get; set; } = new List<TourService>();
}