// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repositories.Models;

public partial class TourService
{
    public int ServiceId { get; set; }

    public string ServiceName { get; set; }

    public float Price { get; set; }

    public TimeOnly Duration { get; set; }

    public string Content { get; set; }

    public string Image { get; set; }

    public int TourGuideId { get; set; }

    public DateOnly CreatedDate { get; set; }

    public bool IsDeleted { get; set; }

    public string Title { get; set; }

    public virtual TourGuide TourGuide { get; set; }
}