// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class AccountMembership
{
    public int AccountMembershipId { get; set; }

    public int AccountId { get; set; }

    public int MembershipPackageId { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public bool IsActive { get; set; }

    public virtual Account Account { get; set; }

    public virtual MembershipPackage MembershipPackage { get; set; }
}