// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class BlogLike
{
    public int BlogLikeId { get; set; }

    public int AccountId { get; set; }

    public int BlogId { get; set; }

    public virtual Account Account { get; set; }

    public virtual Blog Blog { get; set; }
}