// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class Invoice
{
    public int InvoiceId { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public int TourGuideId { get; set; }

    public string PeopleAmount { get; set; }

    public string Status { get; set; }

    public float Price { get; set; }

    public string Note { get; set; }

    public int CustomerId { get; set; }

    public int AreaId { get; set; }

    public string TourDesc { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ActiveArea Area { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual TourGuide TourGuide { get; set; }
}