// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class NewsCategory
{
    public int NewsCategoryId { get; set; }

    public int CategoryId { get; set; }

    public int NewsId { get; set; }

    public virtual Category Category { get; set; }

    public virtual News News { get; set; }
}