// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class NewsReply
{
    public int NewsReplyId { get; set; }

    public string Content { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool IsDeleted { get; set; }

    public int ReplyFor { get; set; }

    public int AccountId { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Account Account { get; set; }

    public virtual NewsComment ReplyForNavigation { get; set; }
}