// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class NewsComment
{
    public int NewsCommentId { get; set; }

    public string Content { get; set; }

    public int? Rating { get; set; }

    public DateTime CreatedDate { get; set; }

    public bool IsDeleted { get; set; }

    public int AccountId { get; set; }

    public int NewsId { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Account Account { get; set; }

    public virtual News News { get; set; }

    public virtual ICollection<NewsReply> NewsReplies { get; set; } = new List<NewsReply>();
}