// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class TourBid
{
    public int TourBid1 { get; set; }

    public int AccountId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public int PlaceRequested { get; set; }

    public string Status { get; set; }

    public string Content { get; set; }

    public float? MaxPrice { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<Bid> Bids { get; set; } = new List<Bid>();

    public virtual ActiveArea PlaceRequestedNavigation { get; set; }
}