// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities.Models;

public partial class TourGuideRevenue
{
    public int TourGuideRevenue1 { get; set; }

    public int PaymentId { get; set; }

    public float Value { get; set; }

    public int TourGuideId { get; set; }

    public virtual Payment Payment { get; set; }

    public virtual TourGuide TourGuide { get; set; }
}